# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
server:
  replicas: 1
ui:
  enabled: true
  service:
    type: NodePort
connectInject:
  enabled: true
controller:
  enabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.5.0"
  managedGatewayClass:
    serviceType: NodePort
    useHostPorts: true
